baseURL: https://www.jackgreenberg.co
languageCode: en-us
title: Jack Greenberg
author: Jack Greenberg
copyright: "Copyright © 2020, Jack Greenberg; all rights reserved."
enableEmoji: true
enableRobotsTXT: true
email: j@jacklgreenberg.com
assetDir: static
params:
  name: Jack Greenberg
  email: j@jacklgreenberg.com
  subtitle: Electrical and Firmware Engineer
  description: The portfolio and personal website for Jack Greenberg. I'm an electrical and firmware engineer studying at Olin College of Engineering.
markup:
  highlight:
    lineNos: true
    lineNumbersInTable: true
    noClasses: false
    style: dracula
    tabWidth: 4
  goldmark:
    extensions:
      footnote: true
outputs:
  page:
    - json
    - html
  section:
    - json
privacy:
  youtube:
    privacyenhanced: true
sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5
disableKinds:
- taxonomy
- taxonomyTerm
