baseURL = "https://jacklgreenberg.com"
languageCode = "en-us"
title = "Jack Greenberg"

[params]
  subtitle = "Electrical and Firmware Engineer"

[markup]
    [markup.highlight]
      lineNos = true
      lineNumbersInTable = true
      noClasses = true
      style = "paraiso-dark"
    [markup.goldmark]
      [markup.goldmark.extensions]
        footnote = true
